/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [5:0] row,
    output reg [5:0] col
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  wire [6-1:0] M_led_multiplexer_row;
  wire [6-1:0] M_led_multiplexer_column;
  wire [1-1:0] M_led_multiplexer_timerout;
  reg [36-1:0] M_led_multiplexer_inp_int;
  led_multiplexer_2 led_multiplexer (
    .clk(clk),
    .rst(rst),
    .inp_int(M_led_multiplexer_inp_int),
    .row(M_led_multiplexer_row),
    .column(M_led_multiplexer_column),
    .timerout(M_led_multiplexer_timerout)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    M_led_multiplexer_inp_int[0+5-:6] = 6'h0c;
    M_led_multiplexer_inp_int[6+5-:6] = 6'h0c;
    M_led_multiplexer_inp_int[12+5-:6] = 6'h0c;
    M_led_multiplexer_inp_int[18+5-:6] = 6'h0c;
    M_led_multiplexer_inp_int[24+5-:6] = 6'h3f;
    M_led_multiplexer_inp_int[30+5-:6] = 6'h3f;
    row = M_led_multiplexer_row;
    col = M_led_multiplexer_column;
    led[0+0-:1] = M_led_multiplexer_timerout;
  end
endmodule
